stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - trust_llm_61
  script:
    - echo "Сборка образов"
    - export HF_CACHE_HOST_PATH="${CI_PROJECT_DIR}/.hf_cache" # Путь на хосте GitLab Runner
    - mkdir -p "${HF_CACHE_HOST_PATH}"
    - export HF_CACHE_HOST_PATH 
    - export HF_HOME=${HF_HOME_CI_PATH_CONTAINER:-/project_cache/huggingface}
    - export TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE_CI_PATH_CONTAINER:-/project_cache/transformers}
    - docker compose -f docker-compose.yml build

deploy:
  stage: deploy
  tags:
    - trust_llm_61
  script:
    - echo "Запуск контейнеров ..."
    - export CURRENT_UID=$(id -u)
    - export CURRENT_GID=$(id -g)
    - docker compose -f docker-compose.yml up -d --build