stages:
  - build
  - deploy

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - docker-compose.yml
        - .gitlab-ci.yml
  tags:
    - trust_llm_61
  script:
    - echo "Сборка образов"
    - docker compose -f docker-compose.yml build

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags:
    - trust_llm_61
  script:
    - echo "Запуск контейнеров ..."
    - export CURRENT_UID=$(id -u)
    - export CURRENT_GID=$(id -g)
    - docker compose -f docker-compose.yml down --remove-orphans
    - docker compose -f docker-compose.yml up -d



