version: '3'

x-common-env: &common-env
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  MONGO_INITDB_ROOT_PORT: ${MONGO_INITDB_ROOT_PORT}
  MONGO_HOST: ${MONGO_HOST}
  YANDEX_API_KEY: ${YANDEX_API_KEY}
  YANDEX_MODEL_URI: ${YANDEX_MODEL_URI}
  YANDEX_BASE_URL: ${YANDEX_BASE_URL}

  OPENAI_KEY: ${OPENAI_KEY}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL}

  API_URL: ${API_URL}
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
  GIGACHAT_BASE_URL: ${GIGACHAT_BASE_URL}

  HF_HOME: ${HF_HOME}
  TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE}

services:  
  langchain_backend:
      build: 
        context: .
        target: back
      user: "${CURRENT_UID}:${CURRENT_GID}" 
      image: trust_gen:back
      environment:
        <<: *common-env
        
      container_name: langchain_backend
      ports:
          - "45321:45321"
      restart: on-failure  
      command: python langchain_back/main.py
      extra_hosts:
      - "host.docker.internal:host-gateway"    
      volumes:
      - /tmp/hf_cache:/tmp/hf_cache 

  runners:
    build:
      context: .
      target: runners
    user: "${CURRENT_UID}:${CURRENT_GID}" 
    image: trust_gen:runners
    environment:
        <<: *common-env
    container_name:  runner_run
    command: >
      bash -c " 
      cd /app &&
        python -m runners.run & 
        python -m runners.run_rta_queuer & 
        python -m runners.task_processor & 
        python -m runners.run_sync & 
        python -m runners.run_regexp &
        python -m runners.run_metrics
      "
    depends_on:
      - langchain_backend
    restart: on-failure  

  streamlit_frontend:
    build: 
      context: .
      target: front
    user: "${CURRENT_UID}:${CURRENT_GID}" 
    image: trust_gen:front
    container_name: monitoring
    environment:
        <<: *common-env
    command: python -m streamlit run monitoring/app_main.py --server.port 27366
    depends_on:
      - langchain_backend
    ports:
      - "27366:27366"
    volumes: 
      - ./monitoring:/app/monitoring/
    restart: on-failure
